### ISSUE TITLE
Indicate whether plan is applicable to gateways / end devices

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-frequency-plans#41]
#### Summary

For each plan we should indicate whether it's applicable to end devices and/or gateway.

#### What is already there? What do you see now?

In the Console you can now select both the `EU_863_870` plan and the `EU_863_870_TTN` plan when registering a gateway. For gateways, these plans are equivalent, but users don't know that, which makes it confusing.

#### What is missing? What do you want to see?

We should only show relevant plans when registering gateways / end devices.

#### How do you propose to implement this?

We'd need to indicate in each frequency plan (or perhaps in the index) whether the plan applies to gateways, end devices or both.

**Comment by NicolasMrad** [comment]
https://github.com/TheThingsNetwork/lorawan-frequency-plans/issues/38

**Comment by KrishnaIyer** [comment]
So we can keep this simple and add a `gateways: {true/false}` field to the index file for the frequency plans: https://github.com/TheThingsNetwork/lorawan-frequency-plans/blob/master/frequency-plans.yml

Clients can then use this to filter out plans.

Here is a list of frequency plans which (I think) are **not** relevant for gateways and hence should be have `gateways: false`.
- `AS_923_925_TTN_AU`
- `EU_863_870_TTN`

We'd need to add a new boolean field to the [`FrequencyPlan`](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.32/pkg/frequencyplans/frequencyplans.go#L325) struct and a new function for the [Store](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.32/pkg/frequencyplans/frequencyplans.go#L574) to return all frequency plans that are relevant for gateways.

**Comment by johanstokking** [comment]
I'll check but basically all that configure stuff other than the frequencies (and data rate for LoRa service channel) that is not already defined in another plan.

So SF9 in RX2 is an example of that.

Als the 6 channel roaming draft is ineffective to filter out. It doesn't hurt for gateways to listen on all 8 channels.

**Comment by KrishnaIyer** [comment]
> @KrishnaIyer do we need to call this new function somewhere or how we want to use it?

Good point. The primary usecase would be the [ListFrequencyPlans RPC](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.32/api/ttn/lorawan/v3/configuration_services.proto#L29-L38). We can add this as an optional flag and filter out non-gateway related plans if the flag is set.

**Comment by halimi** [comment]
> So we can keep this simple and add a `gateways: {true/false}` field to the index file for the frequency plans: https://github.com/TheThingsNetwork/lorawan-frequency-plans/blob/master/frequency-plans.yml. Clients can then use this to filter out plans.
> 
> We'd need to add a new boolean field to the [`FrequencyPlan`](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.32/pkg/frequencyplans/frequencyplans.go#L325) struct and a new function for the [Store](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.32/pkg/frequencyplans/frequencyplans.go#L574) to return all frequency plans that are relevant for gateways.
> 
> Here is a list of frequency plans which (I think) are **not** relevant for gateways and hence should be have `gateways: false`.
> 
> * `AS_923_925_TTN_AU`
> * `EU_863_870_TTN`
> 
> Any others @johanstokking?

@KrishnaIyer I just reread again the description and if we want to add `gateways: false` to the index file instead of each frequency file then I need to change the [`FrequencyPlanDescription`](https://github.com/TheThingsNetwork/lorawan-stack/blob/9ca672378448f0c7d7820a1b6855b4746a15e0f5/pkg/frequencyplans/frequencyplans.go#L517) instead of [`FrequencyPlan`](https://github.com/TheThingsNetwork/lorawan-stack/blob/9ca672378448f0c7d7820a1b6855b4746a15e0f5/pkg/frequencyplans/frequencyplans.go#L325) contrary as the description says above.

Can you please confirm that is the case?

**Comment by KrishnaIyer** [comment]
Hmm I see indeed, I also overlooked this.

**Comment by halimi** [comment]
I've changed the implementation and now it uses the index file.

**Comment by halimi** [comment]
I've tested on `staging1` and it works as expected.

Test steps:
 - Make sure that your cli is using the `staging1` environment.
```
go run ./cmd/ttn-lw-cli use tti.staging1.cloud.thethings.industries
```
 
- Make sure that your cli has the `--gateways-only` flag.
```
go run ./cmd/ttn-lw-cli gateways list-frequency-plans --help
```

 - Get the gateways' frequency plans and count how many plans are there.
```
go run ./cmd/ttn-lw-cli gateways list-frequency-plans | wc -l
```
 
- Get the gateways' frequency plans but filter out the non gateway related plans. Count how many plans in the list. Should be less then the previous one. 
```
go run ./cmd/ttn-lw-cli gateways list-frequency-plans --gateways-only | wc -l
```

 - Get the list again with the filter and check that the `EU_863_870_TTN` is not there.
```
go run ./cmd/ttn-lw-cli gateways list-frequency-plans --gateways-only
```

**Comment by KrishnaIyer** [comment]
Thanks a lot. Good stuff 🚀
