### ISSUE TITLE
Implementation of custom frequency plan

### ISSUE THREAD

**Issue by sanijs** [TheThingsNetwork/lorawan-frequency-plans#42]
#### Summary

https://ibb.co/gyBFvfZ

We need assistance to implement a new custom frequency plan in the EU, which is different from the standard frequency plan which uses the 5 optional channels in 867.1 Mhz - 867.9 Mhz. The plan is to move the 5 optional channels after 868.5 Mhz. We seek advice on where it is best to place the new channels, when we also have to think about the duty cycle being different in the other subbands. The reason for having this custom frequency plan is because we are experiencing a lot of interference from a passive RFID system at one of our locations, which results in poor data rate and high packet loss. 

We have tried it ourselves to come up with a custom frequency plan, and test it on a local LNS in our office (see attached file). It did work on most channels, but for some reason we did not receive any data on 869.3 Mhz. We hope that you can help us with finding a way to best implement a frequency plan so we can have coexistence between LoRaWAN and RFID. We have also found an article which describes this issue in North America

https://lora-developers.semtech.com/uploads/documents/files/Coexistence_of_LoRaWAN_and_UHF_RFID_Final_v3.pdf

#### Why do we need this?
To have coexistence between LoRaWAN and RFID

#### What is already there? What do you see now?

EU_863_870

#### What is missing? What do you want to see?

A new custom frequency plan for EU

#### Environment

The Things Stack Cloud v3.16.2

#### How do you propose to implement this?

Find the best 5 new optional channels after 868.5 Mhz and use them together with 868.1 - 868.5 Mhz.

#### Can you do this yourself and submit a Pull Request?

No

**Comment by johanstokking** [comment]
We’ll handle this is the support ticket. Thanks!
