### ISSUE TITLE
Add FSB1 for CN470

### ISSUE THREAD

**Issue by Achichig** [TheThingsNetwork/lorawan-frequency-plans#44]
#### Summary

Add the FSB1 for CN470 frequency plan

#### Why do we need this?

the main motivation is to avoid to have a lot of dropped join request on this frequency plan.

#### Environment

This is an upgrade of the existing CN470 implementation (Section 2.6.2 on LoRaWAN Regional Parameters v1.0):
![image](https://user-images.githubusercontent.com/101577545/161059609-c25adcfc-7e22-4aae-9b4f-854923dc4af6.png)

#### How do you propose to implement this?

Copy-paste the existing CN470_FSB11 and minus 16MHz to each frequency.

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by NicolasMrad** [comment]
Thank you for contributing to the code!
I have assigned the issue to you, and we're looking forward to check the PR!
