### ISSUE TITLE
Add Singapore Frequency Plan

### ISSUE THREAD

**Issue by PAPRADSG-Yee** [TheThingsNetwork/lorawan-frequency-plans#50]
#### Summary

In Singapore, LoRaWAN network falls in the category of LPWAN with Authorized Frequency Band 920 - 925MHz.
There is no Dwell Time limitation and spectrum access is control by means of Duty Cycle. (=<1% ).
Please refer to attached document Page 17/34.
I would like to request for an additional regional frequency SG920-925 to TTS.

[Singapore_IMDATSSRD.pdf](https://github.com/TheThingsNetwork/lorawan-frequency-plans/files/8628567/Singapore_IMDATSSRD.pdf)

#### Why do we need this?

In TTS v3.17 or earlier, Frequency Plan Asia 920 - 923MHz was used. (Default Dwell Time is disabled)
Application with large Uplink/Downlink Payload can be deployed without problem.
In TTS v3.18, Dwell Time is enabled by default in Frequency Plan Asia 920 - 923MHz causing Uplink/Downlink with large Payload cannot be sent.
Since Singapore does not have Dwell Time limitation, we need to have a Frequency Plan where Dwell Time is disabled by default.

#### What is already there? What do you see now?

Currently there is Asia 915-928 MHz (AS923 Group 1) with only default channels and dwell time disabled.

#### What is missing? What do you want to see?

The current Frequency Plan only has default channels. There is no Sub-bands.

#### Environment

This Frequency Plan will be used in Singapore.
The only available regulatory document is the attached Technical Specification. (Page 17/34)

[Singapore_IMDATSSRD.pdf](https://github.com/TheThingsNetwork/lorawan-frequency-plans/files/8628581/Singapore_IMDATSSRD.pdf)

#### How do you propose to implement this?

I would like to propose for an additional regional frequency SG920-925 to be added.
This plan must have all AS923-1 channels (default channels and it's Sub-bands) with default Dwell Time disabled. 

#### Can you do this yourself and submit a Pull Request?

No

**Comment by adriansmares** [comment]
Hi @PAPRADSG-Yee,

Just to make sure that I understood correctly, you would like the Singapore plan to derive the [`AS_920_923`](https://github.com/TheThingsNetwork/lorawan-frequency-plans/blob/master/AS_920_923.yml) plan, but with dwell time disabled and with the 1% duty cycle explicitly added.

cc @htdvisser in case you have anything to add - specifically if there are some measurements that we may want to do before we create this `SG_920_923_TTN` plan.

**Comment by PAPRADSG-Yee** [comment]
Hi @adriansmares ,

My proposal is just to derive Singapore Plan from the AS_920_923 plan with dwell time disabled.
There is no need to explicitly add the 1% duty cycle.

**Comment by htdvisser** [comment]
If we just take the frequencies from an existing AS923 plan, and only change the duty cycle, I don't think we need to do anything else. I think it would make most sense to derive a `AS_920_923_DC1` (DC1 meaning duty cycle 1%) from `AS_920_923`, same as how we have `AS_920_923_LBT`.

**Comment by PAPRADSG-Yee** [comment]
Hi @adriansmares ,

I would like to follow-up on our request.
When can the Singapore Plan for AS_920_923 with dwell time disabled be implemented?
