### ISSUE TITLE
Beacon settings are not provided in frequency plans

### ISSUE THREAD

**Issue by reissjason** [TheThingsNetwork/lorawan-frequency-plans#64]
#### Summary

Basic station expects the LNS to provide beacon parameters in radio_conf. It makes sense that the LNS would control the beacon parameters as it sets all the radio channels.

Support for beacons settings and tests are available in the current release of the TTN stack.
https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.26/pkg/pfconfig/lbslns/lbslbs_test.go#L151
...

#### Environment

- **Frequency plan:** all
- **Region:** all
- **End device brand, model and firmware:** all
- **Gateway brand, model and firmware:** all
- **Network Server version:** all

#### Steps to Reproduce

1. Connect basic station
2. bcning field is not provided in the radio_conf message as shown in station debug.

#### What is already there? What do you see now?

The bcning field can be sent to basic station since v3.21.2
https://www.thethingsnetwork.org/forum/t/upgrade-to-the-things-network-v3-21-2-completed/58810

https://github.com/TheThingsNetwork/lorawan-stack/blob/98e65a7069fd55593fa20fa5a7f44b15bfeba02d/pkg/pfconfig/lbslns/lbslns.go#L251
...

#### What is missing? What do you want to see?

Beaconing settings in frequency plans or additional plans for optional beaconing.
...

#### How do you propose to implement this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by adriansmares** [comment]
The Things Stack provides the `bcning` since version `3.21.2` (https://github.com/TheThingsNetwork/lorawan-stack/pull/5745), and our automatic testing also checks for this internally

Could you please post some debug Basics Station logs with a version which does not support the `bcning` ? What frequency plans did you test this with ?

**Comment by reissjason** [comment]
Perhaps I was wrong. I am seeing the "bcning" field. We had been testing basic station 2.0.5 which I see has a known issue for transmitted beacon settings. We have updated to 2.0.6 and now see beacons at our end-device and receive downlink in ping slots.

**Comment by reissjason** [comment]
Working after upgrade to Basic Station 2.0.6.
