### ISSUE TITLE
Japan-specific frequency plan

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-frequency-plans#7]
We should add a Japan-specific frequency plan that sets the maximum EIRP correctly (to 16dBm).

**Comment by htdvisser** [comment]
Closing since we'll set the default max EIRP for the entire AS923 band to 16

**Comment by johanstokking** [comment]
@htdvisser @KrishnaIyer can you comment on what we're going to do here? We will have a JP frequency plan with 27 dBm max EIRP on sub-band 920.5 MHz to 923.5 MHz?

**Comment by KrishnaIyer** [comment]
Yeah indeed. I'll pick this up.

**Comment by tooruuetani** [comment]
How is the progress ?
Will this PR be merged by Q1?

**Comment by tooruuetani** [comment]
I made PR for Japanese specific frequencies and it was approved. 
see https://github.com/TheThingsNetwork/lorawan-frequency-plans/pull/36 .

So this issue title "Japan-specific frequency plan" is not suitable. I think to need modify this title to "Japan-specific frequency plan for default MAX EIRP"

I will create another PR later.

And I have a question for MAX EIRP.
If the new frequency plan has like below, does the LoRaWAN network server indicate the power with 27 dBm to our gateways ?

```
band-id: AS_923
sub-bands:
  - min-frequency: 920600000
    max-frequency: 923400000
    max-eirp: 27
```

**Comment by johanstokking** [comment]
> And I have a question for MAX EIRP. If the new frequency plan has like below, does the LoRaWAN network server indicate the power with 27 dBm to our gateways ?

Yes. 

Thanks!

**Comment by tooruuetani** [comment]
Thanks !
I created another PR. See https://github.com/TheThingsNetwork/lorawan-frequency-plans/pull/47 .

**Comment by htdvisser** [comment]
With #36 and #47 merged, I think we can close this. Feel free to re-open if there's still work to do.
